before:
  hooks:
    - go mod tidy
    - go mod vendor
    - go mod download
    - go test -v ./...
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w -X main.build={{.Env.AE_VERSION}} -X 'main.AuthorName={{ .Env.AE_AUTHOR_NAME}}' -X 'main.AuthorEmail={{.Env.AE_AUTHOR_EMAIL}}' -X 'main.Copyright={{.Env.AE_COPYRIGHT}}' -X 'main.License={{.Env.AE_LICENSE}}' -X 'main.Name={{.Env.AE_TARGET}}'

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# TODO: Build docker images with `ae` binaries generated by goreleaser.
#
# dockers:
# - image_templates:
#   - "foo/bar:{{ .Version }}-amd64"
#   - "aurae-runtime/ae:latest-amd64"
#   - "aurae-runtime/ae:{{ .Tag }}-amd64"
#   - "aurae-runtime/ae:v{{ .Major }}-amd64"
#   - "ghcr.io/aurae-runtime/ae:latest-amd64"
#   use: buildx
#   dockerfile: Dockerfile.goreleaser
#   skip_push: true
#   build_flag_templates:
#   - "--platform=linux/amd64"
#   - "--pull"
#   - "--label=org.opencontainers.image.created={{.Date}}"
#   - "--label=org.opencontainers.image.title={{.ProjectName}}"
#   - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#   - "--label=org.opencontainers.image.version={{.Version}}"
# - image_templates:
#    - "aurae-runtime/ae:latest-arm64v8"
#    - "aurae-runtime/ae:{{ .Tag }}-arm64v8"
#    - "aurae-runtime/ae:v{{ .Major }}-arm64v8"
#    - "ghcr.io/aurae-runtime/ae:latest-arm64v8"
#   use: buildx
#   goarch: arm64
#   dockerfile: Dockerfile
#   skip_push: true
#   build_flag_templates:
#     - "--platform=linux/arm64/v8"
#     - "--pull"
#     - "--label=org.opencontainers.image.created={{.Date}}"
#     - "--label=org.opencontainers.image.title={{.ProjectName}}"
#     - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#     - "--label=org.opencontainers.image.version={{.Version}}"
# docker_manifests:
# - name_template: aurae-runtime/ae:{{ .Version }}
#   image_templates:
#   - aurae-runtime/ae:{{ .Version }}-amd64
#   - aurae-runtime/ae:{{ .Version }}-arm64v8
  
