// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: v0/runtime/runtime.proto

package runtimev0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InstanceServiceClient is the client API for InstanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstanceServiceClient interface {
}

type instanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstanceServiceClient(cc grpc.ClientConnInterface) InstanceServiceClient {
	return &instanceServiceClient{cc}
}

// InstanceServiceServer is the server API for InstanceService service.
// All implementations must embed UnimplementedInstanceServiceServer
// for forward compatibility
type InstanceServiceServer interface {
	mustEmbedUnimplementedInstanceServiceServer()
}

// UnimplementedInstanceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInstanceServiceServer struct {
}

func (UnimplementedInstanceServiceServer) mustEmbedUnimplementedInstanceServiceServer() {}

// UnsafeInstanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstanceServiceServer will
// result in compilation errors.
type UnsafeInstanceServiceServer interface {
	mustEmbedUnimplementedInstanceServiceServer()
}

func RegisterInstanceServiceServer(s grpc.ServiceRegistrar, srv InstanceServiceServer) {
	s.RegisterService(&InstanceService_ServiceDesc, srv)
}

// InstanceService_ServiceDesc is the grpc.ServiceDesc for InstanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurae.runtime.v0.InstanceService",
	HandlerType: (*InstanceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "v0/runtime/runtime.proto",
}

// SpawnServiceClient is the client API for SpawnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpawnServiceClient interface {
}

type spawnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpawnServiceClient(cc grpc.ClientConnInterface) SpawnServiceClient {
	return &spawnServiceClient{cc}
}

// SpawnServiceServer is the server API for SpawnService service.
// All implementations must embed UnimplementedSpawnServiceServer
// for forward compatibility
type SpawnServiceServer interface {
	mustEmbedUnimplementedSpawnServiceServer()
}

// UnimplementedSpawnServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSpawnServiceServer struct {
}

func (UnimplementedSpawnServiceServer) mustEmbedUnimplementedSpawnServiceServer() {}

// UnsafeSpawnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpawnServiceServer will
// result in compilation errors.
type UnsafeSpawnServiceServer interface {
	mustEmbedUnimplementedSpawnServiceServer()
}

func RegisterSpawnServiceServer(s grpc.ServiceRegistrar, srv SpawnServiceServer) {
	s.RegisterService(&SpawnService_ServiceDesc, srv)
}

// SpawnService_ServiceDesc is the grpc.ServiceDesc for SpawnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpawnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurae.runtime.v0.SpawnService",
	HandlerType: (*SpawnServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "v0/runtime/runtime.proto",
}

// PodServiceClient is the client API for PodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodServiceClient interface {
	Allocate(ctx context.Context, in *PodServiceAllocateRequest, opts ...grpc.CallOption) (*PodServiceAllocateResponse, error)
	Start(ctx context.Context, in *PodServiceStartRequest, opts ...grpc.CallOption) (*PodServiceStartResponse, error)
	Stop(ctx context.Context, in *PodServiceStopRequest, opts ...grpc.CallOption) (*PodServiceStopResponse, error)
	Free(ctx context.Context, in *PodServiceFreeRequest, opts ...grpc.CallOption) (*PodServiceFreeResponse, error)
}

type podServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPodServiceClient(cc grpc.ClientConnInterface) PodServiceClient {
	return &podServiceClient{cc}
}

func (c *podServiceClient) Allocate(ctx context.Context, in *PodServiceAllocateRequest, opts ...grpc.CallOption) (*PodServiceAllocateResponse, error) {
	out := new(PodServiceAllocateResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.v0.PodService/Allocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podServiceClient) Start(ctx context.Context, in *PodServiceStartRequest, opts ...grpc.CallOption) (*PodServiceStartResponse, error) {
	out := new(PodServiceStartResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.v0.PodService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podServiceClient) Stop(ctx context.Context, in *PodServiceStopRequest, opts ...grpc.CallOption) (*PodServiceStopResponse, error) {
	out := new(PodServiceStopResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.v0.PodService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podServiceClient) Free(ctx context.Context, in *PodServiceFreeRequest, opts ...grpc.CallOption) (*PodServiceFreeResponse, error) {
	out := new(PodServiceFreeResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.v0.PodService/Free", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodServiceServer is the server API for PodService service.
// All implementations must embed UnimplementedPodServiceServer
// for forward compatibility
type PodServiceServer interface {
	Allocate(context.Context, *PodServiceAllocateRequest) (*PodServiceAllocateResponse, error)
	Start(context.Context, *PodServiceStartRequest) (*PodServiceStartResponse, error)
	Stop(context.Context, *PodServiceStopRequest) (*PodServiceStopResponse, error)
	Free(context.Context, *PodServiceFreeRequest) (*PodServiceFreeResponse, error)
	mustEmbedUnimplementedPodServiceServer()
}

// UnimplementedPodServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPodServiceServer struct {
}

func (UnimplementedPodServiceServer) Allocate(context.Context, *PodServiceAllocateRequest) (*PodServiceAllocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedPodServiceServer) Start(context.Context, *PodServiceStartRequest) (*PodServiceStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPodServiceServer) Stop(context.Context, *PodServiceStopRequest) (*PodServiceStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPodServiceServer) Free(context.Context, *PodServiceFreeRequest) (*PodServiceFreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Free not implemented")
}
func (UnimplementedPodServiceServer) mustEmbedUnimplementedPodServiceServer() {}

// UnsafePodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodServiceServer will
// result in compilation errors.
type UnsafePodServiceServer interface {
	mustEmbedUnimplementedPodServiceServer()
}

func RegisterPodServiceServer(s grpc.ServiceRegistrar, srv PodServiceServer) {
	s.RegisterService(&PodService_ServiceDesc, srv)
}

func _PodService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodServiceAllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.v0.PodService/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServiceServer).Allocate(ctx, req.(*PodServiceAllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodServiceStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.v0.PodService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServiceServer).Start(ctx, req.(*PodServiceStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodServiceStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.v0.PodService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServiceServer).Stop(ctx, req.(*PodServiceStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodService_Free_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodServiceFreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServiceServer).Free(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.v0.PodService/Free",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServiceServer).Free(ctx, req.(*PodServiceFreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PodService_ServiceDesc is the grpc.ServiceDesc for PodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurae.runtime.v0.PodService",
	HandlerType: (*PodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _PodService_Allocate_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _PodService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _PodService_Stop_Handler,
		},
		{
			MethodName: "Free",
			Handler:    _PodService_Free_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v0/runtime/runtime.proto",
}

// CellServiceClient is the client API for CellService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CellServiceClient interface {
	// / Reserve requested system resources for a new cell.
	// / For cells specifically this will allocate and reserve cgroup resources
	// / only.
	Allocate(ctx context.Context, in *CellServiceAllocateRequest, opts ...grpc.CallOption) (*CellServiceAllocateResponse, error)
	// / Free up previously requested resources for an existing cell
	Free(ctx context.Context, in *CellServiceFreeRequest, opts ...grpc.CallOption) (*CellServiceFreeResponse, error)
	// / Start a new Executable inside of an existing cell. Can be called
	// / in serial to start more than one executable in the same cell.
	Start(ctx context.Context, in *CellServiceStartRequest, opts ...grpc.CallOption) (*CellServiceStartResponse, error)
	// / Stop one or more Executables inside of an existing cell.
	// / Can be called in serial to stop/retry more than one executable.
	Stop(ctx context.Context, in *CellServiceStopRequest, opts ...grpc.CallOption) (*CellServiceStopResponse, error)
}

type cellServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCellServiceClient(cc grpc.ClientConnInterface) CellServiceClient {
	return &cellServiceClient{cc}
}

func (c *cellServiceClient) Allocate(ctx context.Context, in *CellServiceAllocateRequest, opts ...grpc.CallOption) (*CellServiceAllocateResponse, error) {
	out := new(CellServiceAllocateResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.v0.CellService/Allocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) Free(ctx context.Context, in *CellServiceFreeRequest, opts ...grpc.CallOption) (*CellServiceFreeResponse, error) {
	out := new(CellServiceFreeResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.v0.CellService/Free", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) Start(ctx context.Context, in *CellServiceStartRequest, opts ...grpc.CallOption) (*CellServiceStartResponse, error) {
	out := new(CellServiceStartResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.v0.CellService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) Stop(ctx context.Context, in *CellServiceStopRequest, opts ...grpc.CallOption) (*CellServiceStopResponse, error) {
	out := new(CellServiceStopResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.v0.CellService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CellServiceServer is the server API for CellService service.
// All implementations must embed UnimplementedCellServiceServer
// for forward compatibility
type CellServiceServer interface {
	// / Reserve requested system resources for a new cell.
	// / For cells specifically this will allocate and reserve cgroup resources
	// / only.
	Allocate(context.Context, *CellServiceAllocateRequest) (*CellServiceAllocateResponse, error)
	// / Free up previously requested resources for an existing cell
	Free(context.Context, *CellServiceFreeRequest) (*CellServiceFreeResponse, error)
	// / Start a new Executable inside of an existing cell. Can be called
	// / in serial to start more than one executable in the same cell.
	Start(context.Context, *CellServiceStartRequest) (*CellServiceStartResponse, error)
	// / Stop one or more Executables inside of an existing cell.
	// / Can be called in serial to stop/retry more than one executable.
	Stop(context.Context, *CellServiceStopRequest) (*CellServiceStopResponse, error)
	mustEmbedUnimplementedCellServiceServer()
}

// UnimplementedCellServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCellServiceServer struct {
}

func (UnimplementedCellServiceServer) Allocate(context.Context, *CellServiceAllocateRequest) (*CellServiceAllocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedCellServiceServer) Free(context.Context, *CellServiceFreeRequest) (*CellServiceFreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Free not implemented")
}
func (UnimplementedCellServiceServer) Start(context.Context, *CellServiceStartRequest) (*CellServiceStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedCellServiceServer) Stop(context.Context, *CellServiceStopRequest) (*CellServiceStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedCellServiceServer) mustEmbedUnimplementedCellServiceServer() {}

// UnsafeCellServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CellServiceServer will
// result in compilation errors.
type UnsafeCellServiceServer interface {
	mustEmbedUnimplementedCellServiceServer()
}

func RegisterCellServiceServer(s grpc.ServiceRegistrar, srv CellServiceServer) {
	s.RegisterService(&CellService_ServiceDesc, srv)
}

func _CellService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellServiceAllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.v0.CellService/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).Allocate(ctx, req.(*CellServiceAllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_Free_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellServiceFreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).Free(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.v0.CellService/Free",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).Free(ctx, req.(*CellServiceFreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellServiceStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.v0.CellService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).Start(ctx, req.(*CellServiceStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellServiceStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.v0.CellService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).Stop(ctx, req.(*CellServiceStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CellService_ServiceDesc is the grpc.ServiceDesc for CellService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CellService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurae.runtime.v0.CellService",
	HandlerType: (*CellServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _CellService_Allocate_Handler,
		},
		{
			MethodName: "Free",
			Handler:    _CellService_Free_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _CellService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _CellService_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v0/runtime/runtime.proto",
}
