name: Build Master Release versions

on:
  pull_request:

## Publish a docker image with the CLI? Future use as a runjob maybe?
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aurae-runtime/ae

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    ## needed to publish eventually to GHCR
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and Test using Docker
        run: |
          make docker_pr

#     - name: Log in to the Container registry
#       uses: docker/login-action@v2
#       with:
#         registry: ${{ env.REGISTRY }}
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}



